### ISSUE TITLE
[Bug]: AEWEB upload error 

### ISSUE THREAD

**Issue by Alexrollo64** [archethic-foundation/bug-bounty#20]
### Description

When i'm uploading an html file with aeweb on the mainnet , with a wallet of 100 uco , all seems okay but in the  2nd transaction
"the upload transaction" , it just stops there .
I'm trying to upload a file of 26Ko with a decent internet connection. 
Aeweb just stop at transaction 2 validation

screen of a speedtest ookla at the time of the upload 

### Logs / Images

Creating file structure and compress content...
Spliting file(s) content in multiple transaction if necessary ...
Creating transactions, it may take a while...
Estimating fees...
Total Fee Requirement would be : 2.32 UCO ( $ 0.23 | € 0.23), for 3 transactions.
Do you want to continue. (yes/no) y
Sending 3 transactions...
Transaction 1...
Waiting transaction validation...
Got confirmation
See transaction in explorer: https://mainnet.archethic.net//explorer/transaction/000097091f905e037205029db07818f4885bdc90d20b7751f73bf49c4a0e1b2a0483
Transaction 2...
Waiting transaction validation...

![SpeedTest Ookla 15 07 22 19h18](https://user-images.githubusercontent.com/109369716/179278899-4f79d075-b489-45aa-af64-7102326b901d.JPG)

### Platform

Windows 10 

### Version of Archethic apps

the most recent aeweb

**Comment by Neylix** [comment]
Hello,
Thanks for reporting this bug.
The problem is caused by 2 things: 
- The transaction subscriber do not return transaction error : https://github.com/archethic-foundation/archethic-node/issues/445
- In AEweb CLI the next transaction is sent when we receive the first confirmation of the last transaction, but the transaction is not replicated on all storage node and so the next transaction will encounter an error. I created a new issue for this : https://github.com/archethic-foundation/archethic-node/issues/456

**Comment by Alexrollo64** [comment]
Thanks for your feedback ! 
Appreciate it , waiting for you to patch that , so i'll can go more deep in aeweb uploading .
