### ISSUE TITLE
[Bug]: Menu Improvement when i choose the network

### ISSUE THREAD

**Issue by ElNelyo** [archethic-foundation/bug-bounty#35]
### Description

# Network Choice

On MacOS, when i want to choose a network is not possible to go back to the main menu. 
I must make a choice and continue the process and then go back 

### Logs / Images

<img width="386" alt="Capture d’écran 2022-08-07 à 17 57 15" src="https://user-images.githubusercontent.com/17676307/183300003-532e2222-b100-47d3-9019-f711edb1d1ac.png">
)

### Platform

MacOS

### Version of Archethic apps

1_03

### Fix

Just add a back arrow to close this menu  OR Close this menu on_click outside the box

**Comment by redDwarf03** [comment]
in the beginning of the onboard process, this choice is mandatory
After that, we have some updates planned in the network management
https://github.com/archethic-foundation/archethic-wallet/issues/116
https://github.com/archethic-foundation/archethic-wallet/issues/144

This issue is an UX request. It's out of the scope of bug bounty
