### ISSUE TITLE
wallet : comportement d'affichage selon les blocs affichés

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#8]
### Description

Selon les blocs affichés dans l'interface, le slide sur le bloc des boutons 'envoyer', 'recevoir', 'acheter' + transactions récentes ne se comporte pas toujours de manière identique.

En affichant tous les blocs, il est possible de faire disparaitre les boutons 'envoyer', 'recevoir', 'acheter', en faisant un slide.

En désactivant le blog et le cours, les boutons restent affichés malgré les tentatives de slide.

### Platform

Android

### Version of Archethic apps

1.0.0 DayOne

### Fix

Je trouve qu'il serait agréable que les boutons 'envoyer', 'recevoir', 'acheter' restent affichés quoiqu'il arrive.

**Comment by redDwarf03** [comment]
Hello. Thanks again for your feedback. We will analyze your issue but in other context of bug bounty because it's about user experience.
See https://blog.archethic.net/bugbounty/ _(Archethic wallet, user interface defects related to the type of device, screen resolution or Android version are out of scope)_
