### ISSUE TITLE
wallet : défaut d'affichage d'une transaction émise avec devise à grande décimale

### ISSUE THREAD

**Issue by n0uki63** [archethic-foundation/bug-bounty#9]
### Description

Sur un bloc de transaction récente de type envoi, la ligne indiquant les frais chevauche la valorisation de l'envoi en devise lorsque la devise contient de nombreuses décimales.

Sélectionner le btc pour reproduire.

### Platform

Android

### Version of Archethic apps

1.0.0 DayOne

**Comment by redDwarf03** [comment]
Hello. Thanks again for your feedback. We will analyze your issue but in other context of bug bounty because it's about user experience.
See https://blog.archethic.net/bugbounty/ (Archethic wallet, user interface defects related to the type of device, screen resolution or Android version are out of scope)
